runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /_ah/spi/.*
  script: api.api

- url: /crons/send_reminder
  script: main.app

- url: /sendtestemail
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: endpoints
  version: latest